### ISSUE TITLE
ER_TRUNCATED_WRONG_VALUE error when trying to create test data

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#100] opened 2015-01-12 17:57 UTC
Per https://github.com/mozilla/chronicle/issues/98#issuecomment-69433964

After the #99 bug fix, I can create the database as expected (`$ node server/db/create_db.js`), but running `$ node server/db/create_test_data.js` gives me a hard error of:

```
chronicle.db.createTestUser.VERBOSE: inserted fake user into db
chronicle.CRITICAL: Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2015-01-01T21:26:23.795Z' for column 'visitedAt' at row 1
```

Full log is:
```
$ node server/db/create_test_data.js
chronicle.server.db.utils.VERBOSE: pool "connection" event fired, setting timezone
chronicle.db.createTestUser.VERBOSE: truncated visits table
chronicle.db.createTestUser.VERBOSE: truncated users table
chronicle.db.createTestUser.VERBOSE: fakeUser is {"id":"a6c9411418f94710a712ab97e7a3541c","email":"fake_user@example.com","oauthToken":"fakeOauthToken"}
chronicle.server.db.db.VERBOSE: db.createUser called. arguments are: a6c9411418f94710a712ab97e7a3541c, fake_user@example.com, fakeOauthToken, function (err) {
    if (err) { throw err; }
    log.verbose('inserted fake user into db');

    // instead of db.createVisit, we'll just issue a bulk insert query directly
    var query = 'INSERT INTO visits (id, visitedAt, fxaId, rawUrl, url, urlHash, title) ' +
                'VALUES ?';
    log.trace('about to insert bulk data');
    log.trace('query is: ' + query);
    log.trace('bulkData.length is ' + bulkData.length);
    pool.query(query, [bulkData], function(err) {
      if (err) { throw err; }
      log.verbose('inserted ' + bulkData.length + ' user visits into db');
      cb && cb(err);
    });
  }
chronicle.server.db.utils.VERBOSE: pool "connection" event fired, setting timezone
chronicle.server.db.db.VERBOSE: db.createUser: created user called. arguments are: undefined
chronicle.db.createTestUser.VERBOSE: inserted fake user into db
chronicle.CRITICAL: Error: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2015-01-01T21:26:23.795Z' for column 'visitedAt' at row 1
    at Query.Sequence._packetToError (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    --------------------
    at Pool.query (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/Pool.js:180:23)
    at /Users/pdehaan/dev/github/chronicle/server/db/create_test_data.js:70:10
    at Query._callback (/Users/pdehaan/dev/github/chronicle/server/db/db.js:36:7)
    at Query.Sequence.end (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.OkPacket (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/protocol/sequences/Query.js:77:10)
    at Protocol._parsePacket (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/pdehaan/dev/github/chronicle/node_modules/mysql/lib/Connection.js:82:28)
chronicle.server.db.utils.VERBOSE: received exit signal, closing pool
chronicle.server.db.utils.VERBOSE: received exit signal, closing pool
```

MySQL Server version: 5.6.22 Homebrew running on OS X Yosemite (10.10.1)

**Comment by 6a68** [comment] 2015-01-12 19:24
what specifically is the output of `mysql --version`? I get:

```bash
jareds-partybus:mozilla-chronicle jhirsch$ mysql --version
mysql  Ver 14.14 Distrib 5.6.22, for osx10.9 (x86_64) using  EditLine wrapper
```

**Comment by 6a68** [comment] 2015-01-12 19:27
@pdehaan also, do you have any config files in any of the locations mentioned by `mysql --help`? I believe these should be: `/etc/my.cnf /etc/mysql/my.cnf /usr/local/etc/my.cnf ~/.my.cnf`

Homebrew does not insert a my.cnf file by default, but it's possible you have one from another mysql installation.

**Comment by edmoz** [comment] 2015-01-12 19:38
from 6a68 suggestion, I removed this `,STRICT_TRANS_TABLES`

from here:
/usr/local/Cellar/mysql/5.6.22

restarted mysql and everything is working for me.

**Comment by 6a68** [comment] 2015-01-12 19:50
caused by homebrew inserting a my.cnf file in a nonstandard location :-(

closing as dupe of the WONTFIX'd https://github.com/Homebrew/homebrew/issues/26060

I hate mysql

**Closed by 6a68** 2015-01-12 19:50 UTC
Labels: server

**Comment by pdehaan** [comment] 2015-01-12 20:19
+1. I got this working following @edmoz's https://github.com/mozilla/chronicle/issues/100#issuecomment-69631341

**Comment by pdehaan** [comment] 2015-01-12 20:21
@6a68 Is there a way we can work w/ a different (non-ISO format) date format that'd work without requiring users to edit buried, global homebrew files?

**Comment by 6a68** [comment] 2015-01-12 20:35
@pdehaan the real problem here is that mysql changed the default my.cnf in a significant way in a micro (5.6.8) release. I think I have a better long-term solution, we'll just use postgres.

**Comment by pdehaan** [comment] 2015-01-12 22:33
Current status:
![](https://31.media.tumblr.com/da98a45e93394c419ce34815cfa4865b/tumblr_inline_nha7l3Gajs1r79k32.gif)
